<?php
$secteurs = [
    "Administration",
    "Agribusiness",
    "Agriculture",
    "Art et Culture",
    "Assurance",
    "Audit et Conseil",
    "Autre",
    "Automobile",
    "Aéronautique",
    "Biotechnologie",
    "Blockchain et Cryptomonnaie",
    "BTP",
    "Cinéma",
    "Commerce",
    "Communication",
    "Consulting",
    "Cybersécurité",
    "Data et Statistiques",
    "Développement durable",
    "Droit",
    "E-sport et Streaming",
    "Édition et Publication",
    "Éducation",
    "Énergies renouvelables",
    "Énergie",
    "Environnement",
    "Événementiel",
    "Finance",
    "Finance et Comptabilité",
    "Formation en ligne et EdTech",
    "Gastronomie",
    "Gestion de patrimoine",
    "Gestion de projet",
    "Immobilier",
    "Industrie",
    "Informatique",
    "Ingénierie",
    "Infrastructures",
    "Innovation et Startups",
    "Intelligence Artificielle et Data Science",
    "Jeux Vidéo",
    "Jeux de société",
    "Logistique",
    "Luxe et Mode",
    "Marketing",
    "Marketing et Communication",
    "Médias",
    "Mode",
    "Musique",
    "Pharmaceutique",
    "Radio",
    "Recherche et Développement",
    "Restauration",
    "Ressources Humaines",
    "Santé",
    "Sciences et Technologies",
    "Sécurité",
    "Service client et support technique",
    "Services Publics",
    "Services à la Personne",
    "Social et Humanitaire",
    "Sport",
    "Télécommunications",
    "Télévision",
    "Tourisme",
    "Transport",
    "Transport maritime",
    "Vente"
];
?>
