<?php
$secteurs = [
    "Informatique",
    "Finance",
    "Marketing",
    "Santé",
    "Éducation",
    "Industrie",
    "Commerce",
    "Art et Culture",
    "Tourisme",
    "Agriculture",
    "BTP",
    "Transport",
    "Télécommunications",
    "Ressources Humaines",
    "Logistique",
    "Énergie",
    "Environnement",
    "Finance et Comptabilité",
    "Marketing et Communication",
    "Vente",
    "Recherche et Développement",
    "Administration",
    "Droit",
    "Ingénierie",
    "Architecture",
    "Sciences et Technologies",
    "Services à la Personne",
    "Services Publics",
    "Médias",
    "Sport",
    "Mode",
    "Gastronomie",
    "Automobile",
    "Aéronautique",
    "Pharmaceutique",
    "Biotechnologie",
    "Infrastructures",
    "Télévision",
    "Radio",
    "Cinéma",
    "Musique",
    "Jeux Vidéo",
    "Événementiel",
    "Assurance",
    "Immobilier",
    "Consulting",
    "Sécurité",
    "Restauration",
    "Agribusiness",
    "Blockchain et Cryptomonnaie",
    "Cybersécurité",
    "Intelligence Artificielle et Data Science",
    "E-sport et Streaming",
    "Énergies renouvelables",
    "Gestion de projet",
    "Service client et support technique",
    "Développement durable",
    "Audit et Conseil",
    "Social et Humanitaire",
    "Innovation et Startups",
    "Édition et Publication",
    "Formation en ligne et EdTech",
    "Gestion de patrimoine",
    "Autre"
];
